import phone from "../Images/phone.png";
import iphone from "../Images/iPhone.png";
import airPods from "../Images/airPods.png";
import galaxy from "../Images/galaxy.png";

export const products = [
  {
    id: 1,
    name: "Смартфон Samsung Galaxy A32 4/64GB Black",
    image: phone,
    images: [iphone, phone, airPods, galaxy],
    isGift: true,
    isDiscount: true,
    isUpdated: false,
    price: 7300000,
    monthly: 2435000,
    month: 24,
  },
  {
    id: 2,
    name: "Смартфон Apple iphone 12 64GB Black",
    image: iphone,
    isGift: false,
    images: [iphone, phone, airPods, galaxy],
    isDiscount: false,
    isUpdated: true,
    price: 7300000,
    monthly: 2435000,
    month: 24,
  },
  {
    id: 3,
    name: "Наушники Apple Airpod Pro",
    image: airPods,
    isGift: false,
    images: [iphone, phone, airPods, galaxy],
    isDiscount: false,
    isUpdated: true,
    price: 7300000,
    monthly: 2435000,
    month: 24,
  },
  {
    id: 4,
    name: "Samsung Galaxy Z Fold2 5G 256GB Mystic Bronze",
    image: galaxy,
    images: [iphone, phone, airPods, galaxy],
    isGift: true,
    isDiscount: true,
    isUpdated: false,
    price: 7300000,
    monthly: 2435000,
    month: 24,
  },
  {
    id: 5,
    name: "Смартфон Apple iphone",
    image: iphone,
    isGift: false,
    images: [iphone, phone, airPods, galaxy],
    isDiscount: false,
    isUpdated: true,
    price: 7300000,
    monthly: 2435000,
    month: 24,
  },
  {
    id: 6,
    name: "Смартфон Samsung Galaxy A32 4/64GB Black",
    image: phone,
    images: [iphone, phone, airPods, galaxy],
    isGift: true,
    isDiscount: true,
    isUpdated: false,
    price: 7300000,
    monthly: 2435000,
    month: 24,
  },
  {
    id: 7,
    name: "Смартфон Apple iphone 12 64GB Black",
    image: iphone,
    isGift: false,
    images: [iphone, phone, airPods, galaxy],
    isDiscount: false,
    isUpdated: true,
    price: 7300000,
    monthly: 2435000,
    month: 24,
  },
  {
    id: 8,
    name: "Наушники Apple Airpod Pro",
    image: airPods,
    isGift: false,
    images: [iphone, phone, airPods, galaxy],
    isDiscount: false,
    isUpdated: true,
    price: 7300000,
    monthly: 2435000,
    month: 24,
  },
  {
    id: 9,
    name: "Samsung Galaxy Z Fold2 5G 256GB Mystic Bronze",
    image: galaxy,
    images: [iphone, phone, airPods, galaxy],
    isGift: true,
    isDiscount: true,
    isUpdated: false,
    price: 7300000,
    monthly: 2435000,
    month: 24,
  },
  {
    id: 10,
    name: "Смартфон Apple iphone",
    image: iphone,
    isGift: false,
    images: [iphone, phone, airPods, galaxy],
    isDiscount: false,
    isUpdated: true,
    price: 7300000,
    monthly: 2435000,
    month: 24,
  },
];
