import phone from "../Images/phone.png";
import iphone from "../Images/iPhone.png";
import airPods from "../Images/airPods.png";
import galaxy from "../Images/galaxy.png";
export const products = [
  {
    id: 1,
    name: "Смартфон Samsung G...",
    image: phone,
    isGift: true,
    isDiscount: true,
    isUpdated: false,
    price: 7300000,
    monthly: 2435000,
    month: 24,
  },
  {
    id: 2,
    name: "Смартфон Apple iphon...",
    image: iphone,
    isGift: false,
    isDiscount: false,
    isUpdated: true,
    price: 7300000,
    monthly: 2435000,
    month: 24,
  },
  {
    id: 3,
    name: "Наушники Apple Airpo...",
    image: airPods,
    isGift: false,
    isDiscount: false,
    isUpdated: true,
    price: 7300000,
    monthly: 2435000,
    month: 24,
  },
  {
    id: 4,
    name: "Samsung Galaxy Z Fold...",
    image: galaxy,
    isGift: true,
    isDiscount: true,
    isUpdated: false,
    price: 7300000,
    monthly: 2435000,
    month: 24,
  },
  {
    id: 5,
    name: "Смартфон Apple iphon...",
    image: iphone,
    isGift: false,
    isDiscount: false,
    isUpdated: true,
    price: 7300000,
    monthly: 2435000,
    month: 24,
  },
  {
    id: 6,
    name: "Смартфон Samsung G...",
    image: phone,
    isGift: true,
    isDiscount: true,
    isUpdated: false,
    price: 7300000,
    monthly: 2435000,
    month: 24,
  },
  {
    id: 7,
    name: "Смартфон Apple iphon...",
    image: iphone,
    isGift: false,
    isDiscount: false,
    isUpdated: true,
    price: 7300000,
    monthly: 2435000,
    month: 24,
  },
  {
    id: 8,
    name: "Наушники Apple Airpo...",
    image: airPods,
    isGift: false,
    isDiscount: false,
    isUpdated: true,
    price: 7300000,
    monthly: 2435000,
    month: 24,
  },
  {
    id: 9,
    name: "Samsung Galaxy Z Fold...",
    image: galaxy,
    isGift: true,
    isDiscount: true,
    isUpdated: false,
    price: 7300000,
    monthly: 2435000,
    month: 24,
  },
  {
    id: 10,
    name: "Смартфон Apple iphon...",
    image: iphone,
    isGift: false,
    isDiscount: false,
    isUpdated: true,
    price: 7300000,
    monthly: 2435000,
    month: 24,
  },
];
